name: Deploy with DeployAja

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy Application
        uses: deployaja/deployaja-cli@v1
        with:
          command: 'deploy'
          api-token: ${{ secrets.DEPLOYAJA_API_TOKEN }}
          environment: 'production'
          project-name: 'gatotkaca-14-app' 