name: Deploy to DeployAja (Manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DeployAja
        uses: deployaja/github-action@v1
        with:
          api_token: ${{ secrets.DEPLOYAJA_API_TOKEN }}
          project: gatotkaca-14-app
          config: deployaja.yaml 