name: Deploy with DeployAja

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to DeployAja via API
        run: |
          # PENTING: Ganti URL di bawah ini dengan URL API dari DeployAja
          curl -k -X POST \
            -H "Authorization: Bearer ${{ secrets.DEPLOYAJA_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "project": "gatotkaca-14-app"
            }' \
            https://api.deployaja.id/v1/deployments 